# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - burgerapp(test)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1df0e91b514d435b8cb6b5b1b4319710 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b592de71d6ab482e9ab2da6ac7577453 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1df0e91b514d435b8cb6b5b1b4319710 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'burgerapp'
        slot-name: 'test'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5f68b40b31c94d049156f4308013412f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1df0e91b514d435b8cb6b5b1b4319710 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'