# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - module3

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_49a7e45ec58f42d6a1d2e302b04f9baf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c085fd9184ad43e28c5fb3c1788cb943 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_49a7e45ec58f42d6a1d2e302b04f9baf }}/nginx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'module3'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9017508d27034dd5b8b626de6aa64237 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_49a7e45ec58f42d6a1d2e302b04f9baf }}/nginx:${{ github.sha }}'